name: Build Clang 

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Cleanup
        run: |
          wget https://raw.githubusercontent.com/Redmi-S2-Y2-Resources/ClangCI/main/clean.sh
          bash clean.sh

      - name: Setup Env
        run: |
          wget https://raw.githubusercontent.com/Redmi-S2-Y2-Resources/ClangCI/main/env.sh
          bash env.sh

      steps:
      - name: Initializing environment
        run: |
          git config --global user.name "shenprjkt"
          git config --global user.email "shenprjktplayground@gmail.com"